Delete product method created
devops-foxtrot-s17/inventory pull request #10
Opened 2017-02-22 21:11 UTC by omersolmazer

Delete product method is available for review

2017-02-22 21:14 UTC, BobZcao approved these changes
Thank you for implementing the DELETE. Actually I am doing that part.

2017-02-22 21:15 UTC, p2hang requested changes
Looks good, just one tiny problem might need fix.

2017-02-22 21:15 UTC, plzhang commented on server.py
> +@app.route('inventory/products/<int:id>', methods=['DELETE'])
Looks good!
Just one thing I'm not sure about, should we have the '/' before the `inventory/products/`?
like `/inventory/products/<int:id>`

2017-02-22 21:34 UTC, pinocchiochang approved these changes
OK. Approved.

2017-02-22 21:35 UTC, pinocchiochang approved these changes
Good to me.

2017-02-24 19:39 UTC, p2hang approved these changes
Looks good!

2017-02-24 19:39 UTC, omersolmazer commented
Code updated with reviews

2017-02-24 19:39 UTC, merged